export const FETCH_PC_MANUFACTURERS = "PC/MANUFACTURERS"
export const FETCH_PC_COMPONENTS = "PC/COMPONENTS"
export const FETCH_PC_COMPONENTS_MOTHERBOARDS = "PC/COMPONENT/MOTHERBOARD"
export const FETCH_PC_COMPONENTS_GPUS = "PC/COMPONENT/MOTHERBOARD"

export const SHOW_LOADER = "APP/SHOW_LOADER"
export const HIDE_LOADER = "APP/HIDE_LOADER"

export const REGISTER_REQUEST = "USERS_REGISTER_REQUEST"
export const REGISTER_SUCCESS = "USERS_REGISTER_SUCCESS"
export const REGISTER_FAILURE = "USERS_REGISTER_FAILURE"

export const LOGIN_REQUEST = "USERS_LOGIN_REQUEST"
export const LOGIN_SUCCESS = "USERS_LOGIN_SUCCESS"
export const LOGIN_FAILURE = "USERS_LOGIN_FAILURE"

export const LOGOUT = "USERS_LOGOUT"
